import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Index from "@/context/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Index>
          <div className="w-[100vw] h-[100vh] bg-[rgba(0,0,0,0.8)]">
            <Navbar />
            {children}
          </div>
        </Index>
      </body>
    </html>
  );
}
